sub main()
    ' TESTS (uncomment to run)
    ' testSuite() : return

    screen = CreateObject("roSGScreen")
    port = CreateObject("roMessagePort")
    screen.setMessagePort(port)
    screen.CreateScene("Demo")
    screen.show() ' vscode_rale_tracker_entry

    while true
        msg = wait(0, port)
        msgType = type(msg)
        if msgType = "roSGScreenEvent"
            if msg.isScreenClosed() then return
        end if
    end while
end sub
